package org.example.util;

import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;

/**
 * Utility class for database operations.
 * Handles configuration, connections, and schema management.
 */
public class DatabaseHelper {
    private static final Properties PROPERTIES = new Properties();
    private static final String CONFIG_FILE = "/db.properties";

    static {
        try (InputStream is = DatabaseHelper.class.getResourceAsStream(CONFIG_FILE)) {
            if (is == null) {
                throw new RuntimeException("Configuration file not found: " + CONFIG_FILE);
            }
            PROPERTIES.load(is);
        } catch (IOException e) {
            throw new RuntimeException("Failed to load database properties", e);
        }
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(
                PROPERTIES.getProperty("db.url"),
                PROPERTIES.getProperty("db.user"),
                PROPERTIES.getProperty("db.password")
        );
    }

    /**
     * Standard initialization for the main application.
     */
    public static void initializeDatabase() {
        executeSchema(false);
    }

    /**
     * Special initialization for tests.
     * Ensures tables exist and are empty.
     */
    public static void forceInitializeTestDatabase() {
        executeSchema(true);
    }

    private static void executeSchema(boolean truncate) {
        String createUsers = "CREATE TABLE IF NOT EXISTS users (" +
                "nickname VARCHAR(100) PRIMARY KEY, " +
                "password VARCHAR(100) NOT NULL, " +
                "email VARCHAR(100) UNIQUE NOT NULL);";

        String createPosts = "CREATE TABLE IF NOT EXISTS posts (" +
                "post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "author_nickname VARCHAR(100) REFERENCES users(nickname), " +
                "content TEXT NOT NULL, " +
                "likes_count INT DEFAULT 0, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);";

        String createLikes = "CREATE TABLE IF NOT EXISTS post_likes (" +
                "post_id INT NOT NULL, " +
                "user_nickname VARCHAR(100) NOT NULL, " +
                "PRIMARY KEY (post_id, user_nickname), " +
                "FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE, " +
                "FOREIGN KEY (user_nickname) REFERENCES users(nickname) ON DELETE CASCADE);";

        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(createUsers);
            stmt.execute(createPosts);
            stmt.execute(createLikes);

            if (truncate) {
                String dbName = conn.getMetaData().getDatabaseProductName();
                if ("H2".equalsIgnoreCase(dbName)) {
                    stmt.execute("SET REFERENTIAL_INTEGRITY FALSE");
                    stmt.execute("TRUNCATE TABLE post_likes");
                    stmt.execute("TRUNCATE TABLE posts");
                    stmt.execute("TRUNCATE TABLE users");
                    stmt.execute("SET REFERENTIAL_INTEGRITY TRUE");
                } else {
                    stmt.execute("TRUNCATE TABLE post_likes, posts, users CASCADE");
                }
                stmt.execute("ALTER TABLE posts ALTER COLUMN post_id RESTART WITH 1");
            }
        } catch (SQLException e) {
            throw new RuntimeException("Database setup failed", e);
        }
    }
}